In [4]:
import os 
os.chdir("/Users/mac/Desktop/Dinger")

In [5]:
import pandas as pd 
import numpy as np
import FinanceDataReader as fdr

from resnet import *
from tqdm import tqdm
from utils import *
from Dinger.universe_module_us import StockUniverse_US
from Dinger.universe_module_kr import StockUniverse_KR
from Dinger.database_module import *

### 미국

In [ ]:
sp500_list = fdr.StockListing('S&P500')

In [8]:
df = pd.read_csv('DF/sp500_score_df.csv', index_col=0)
df

    Symbol                  Name                  Sector  ...  Price  Beta  DIVIDEND
0      MMM                    3M             Industrials  ... 122.83  0.99      4.80
1      AOS           A. O. Smith             Industrials  ...  55.01  1.19      1.99
2      ABT                Abbott             Health Care  ... 106.36  0.71      1.72
3     ABBV                AbbVie             Health Care  ... 141.21  0.68      3.97
4     ABMD               Abiomed             Health Care  ... 266.36  1.37       NaN
..     ...                   ...                     ...  ...    ...   ...       ...
498    YUM           Yum! Brands  Consumer Discretionary  ... 114.42  1.03      1.94
499   ZBRA    Zebra Technologies  Information Technology  ... 293.50  1.67       NaN
500    ZBH         Zimmer Biomet             Health Care  ... 116.83  1.15      0.80
501   ZION  Zions Bancorporation              Financials  ...  57.30  1.23      2.86
502    ZTS                Zoetis             Health Care  ... 162.16  0.76      0.78

[503 rows x 15 columns]

In [9]:
test = StockUniverse_US(stock_list = sp500_list)

In [10]:
test.get_standard_df(df, mode = 'median')
test.get_standard_df(df)

                                Sales       Revenue  ...  Beta  DIVIDEND
Sector                                               ...
Communication Services 57971923076.92 8395573913.04  ...  0.99      3.41
Consumer Discretionary 33889655172.41 2863767241.38  ...  1.36      2.22
Consumer Staples       56689375000.00 3372162500.00  ...  0.56      2.77
Energy                 63800952380.95 7438857142.86  ...  1.65      3.42
Financials             18689313846.15 4360496923.08  ...  1.08      2.38
Health Care            44730625000.00 3760759375.00  ...  0.90      1.67
Industrials            20487042253.52 1966200000.00  ...  1.15      1.63
Information Technology 22266842105.26 5027756578.95  ...  1.18      1.92
Materials              17785714285.71 2059400000.00  ...  1.08      2.30
Real Estate             4390322580.65  966806451.61  ...  0.90      3.42
Utilities              13066551724.14 1422882142.86  ...  0.50      2.84

[11 rows x 11 columns]

In [11]:
cnn_score = pd.read_csv('DF/cnn_score_df.csv', index_col =0)
cnn_score = cnn_score.to_dict('dict')['0']

In [12]:
scored_df = test.add_cnn_score(df, cnn_score)

In [14]:
scored_df2 = test.get_score(scaling = "mm")
scored_df2

MinMax scaler 적용한 scored_df를 csv로 저장합니다.

    Symbol                  Name  ... cnn_score total_score
0      MMM                    3M  ...      0.00        1.76
1      AOS           A. O. Smith  ...      0.00        1.45
2      ABT                Abbott  ...      0.00        1.49
3     ABBV                AbbVie  ...      0.00        1.81
4     ABMD               Abiomed  ...      0.00        1.35
..     ...                   ...  ...       ...         ...
498    YUM           Yum! Brands  ...      0.00        1.53
499   ZBRA    Zebra Technologies  ...      0.00        1.36
500    ZBH         Zimmer Biomet  ...      0.00        1.20
501   ZION  Zions Bancorporation  ...      0.00        1.36
502    ZTS                Zoetis  ...      0.00        1.32

[503 rows x 17 columns]