In [1]:
import os
os.chdir('/Users/seongyeon-kim/Desktop/Dinger')

### 프로젝트 root로 설정

In [2]:
import warnings
warnings.filterwarnings('ignore')

print("현재 디렉토리 " , os.getcwd())

from tqdm import tqdm
import pandas as pd 

from Dinger import universe_module as um

현재 디렉토리  /Users/seongyeon-kim/Desktop/Dinger

In [3]:
import numpy as np

In [4]:
data = pd.read_csv('./data/stock_kr.csv')

In [5]:
data = um.Universe(data)

In [6]:
data.get_standard_df()

,MKT_VAL,PER,PBR,DIV,매출액,영업이익,당기순이익,ROA,ROE,베타
SEC_NM_KOR,,,,,,,,,,
IT,791627.557377,30.229590,2.360836,0.732951,2878.657895,391.440199,298.204319,2.647245,3.790985,1.008083
건강관리,379416.789298,29.659097,4.394548,0.548194,531.131488,47.105085,42.718644,-1.927517,-1379.627517,0.962050
경기관련소비재,376036.335211,20.016451,1.509211,1.401099,4230.656338,267.667614,255.566952,1.603390,1.901977,0.879725
금융,693963.971429,4.575571,0.470429,2.430429,25240.130952,1501.511364,1207.558140,1.116535,5.943307,0.541356
산업재,397119.858357,42.648584,1.739122,1.447479,5455.050992,419.566572,313.157143,3.062678,2.823932,0.897877
소재,461972.765217,16.407696,1.454826,1.640217,4459.973913,374.868421,305.118943,6.362609,10.500435,0.867022
에너지,640968.459459,25.066757,1.930000,1.471351,16468.756757,1935.648649,1259.027027,1.536111,2.755556,0.799710
유틸리티,669974.588235,34.691765,1.293529,2.681765,18977.235294,-3598.529412,-2754.823529,3.247059,5.852941,0.392353
커뮤니케이션서비스,948847.473684,27.989211,2.277632,0.758509,2445.026316,232.646018,134.596491,0.536842,-0.780702,0.936200
필수소비재,273107.592233,19.430680,1.387864,1.585922,3764.941748,260.450000,177.689320,2.388350,3.788350,0.734272

In [7]:
data.get_score()

           종목명 SEC_NM_KOR     업종명    시장구분  Score
종목코드
5380       현대차    경기관련소비재    운수장비   KOSPI    8.0
270         기아    경기관련소비재    운수장비   KOSPI    8.0
12330    현대모비스    경기관련소비재    운수장비   KOSPI    8.0
51900   LG생활건강    경기관련소비재      화학   KOSPI    8.0
90430   아모레퍼시픽    경기관련소비재      화학   KOSPI    6.0
...        ...        ...     ...     ...    ...
33200      모아텍         IT    IT부품  KOSDAQ    1.0
9140      경인전자         IT    전기전자   KOSPI    4.0
17250      인터엠         IT  일반전기전자  KOSDAQ    0.0
32960     동일기연         IT    IT부품  KOSDAQ    3.0
321260    프로이천         IT  일반전기전자  KOSDAQ    3.0

[2138 rows x 5 columns]

In [9]:
from sklearn.preprocessing import StandardScaler

In [11]:
data = pd.read_csv('./data/stock_kr.csv')

In [14]:
if '종목코드' in data.columns:
    data.set_index('종목코드', inplace=True)

data.dropna(inplace=True)

gubun = data[['종목명','SEC_NM_KOR','업종명','시장구분']]
sector_list = data.SEC_NM_KOR.unique()

In [15]:
scaler = StandardScaler()
data.drop(gubun.columns.tolist(), axis=1, inplace=True)
data.drop('ALL_MKT_VAL', axis=1, inplace=True)
scaled_data = scaler.fit_transform(data)

In [19]:
data.columns

Index(['MKT_VAL', 'PER', 'PBR', 'DIV', '매출액', '영업이익', '당기순이익', 'ROA', 'ROE',
       '베타'],
      dtype='object')

In [23]:
scaled_data = pd.DataFrame(scaled_data, columns=data.columns).set_index(data.index)

In [25]:
scaled_data = gubun.merge(scaled_data, right_index=True, left_index=True)

### 스케일링 후

In [29]:
scaled_data.describe().T

,count,mean,std,min,25%,50%,75%,max
MKT_VAL,2138.0,-1.778538e-17,1.000234,-0.095551,-0.088563,-0.082387,-0.064998,43.195627
PER,2138.0,3.554479e-17,1.000234,-0.125980,-0.125980,-0.089228,-0.045591,40.747997
PBR,2138.0,-6.885018e-17,1.000234,-0.389764,-0.260518,-0.162660,0.023824,36.635615
DIV,2138.0,-7.963176e-16,1.000234,-0.656429,-0.656429,-0.435159,0.334020,11.861166
매출액,2138.0,-1.818782e-17,1.000234,-0.179651,-0.173552,-0.163495,-0.124845,29.204609
영업이익,2138.0,1.529672e-16,1.000234,-16.718601,-0.092908,-0.086657,-0.067903,35.876610
당기순이익,2138.0,1.228749e-17,1.000234,-15.819584,-0.092933,-0.084151,-0.063742,36.008239
ROA,2138.0,3.479183e-17,1.000234,-8.330413,-0.258735,0.078925,0.424624,8.021971
ROE,2138.0,-6.213523e-18,1.000234,-46.227466,0.021100,0.022001,0.022802,0.038234
베타,2138.0,6.792197e-17,1.000234,-3.610337,-0.654906,0.024843,0.615929,8.300048

### 스케일링 전

In [32]:
data.describe().T

,count,mean,std,min,25%,50%,75%,max
MKT_VAL,2138.0,578216.255379,6.041336e+06,1096.00,43302.250,80606.00,185631.250,2.614765e+08
PER,2138.0,27.354181,2.171816e+02,0.00,0.000,7.98,17.455,8.875000e+03
PBR,2138.0,2.110968,5.417282e+00,0.00,0.700,1.23,2.240,2.005300e+02
DIV,2138.0,1.245987,1.898572e+00,0.00,0.000,0.42,1.880,2.376000e+01
매출액,2138.0,4704.222170,2.628049e+04,-16.00,144.250,408.50,1424.000,7.720360e+05
영업이익,2138.0,361.128157,3.920152e+03,-65163.00,-3.000,21.50,95.000,1.409700e+05
당기순이익,2138.0,279.725444,3.075246e+03,-48358.00,-6.000,21.00,83.750,1.109880e+05
ROA,2138.0,2.318288,1.244146e+01,-101.30,-0.900,3.30,7.600,1.021000e+02
ROE,2138.0,-188.490271,8.860490e+03,-409690.70,-1.575,6.40,13.500,1.502000e+02
베타,2138.0,0.911594,3.384393e-01,-0.31,0.690,0.92,1.120,3.720000e+00

In [8]:
data.get_score(mode='std')

TypeError: Can only merge Series or DataFrame objects, a <class 'numpy.ndarray'> was passed